// <auto-generated />
using System;
using LAFABRICA.Data.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LAFABRICA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251019015306_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LAFABRICA.Data.DB.Administrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("IDENTIFICATION");

                    b.Property<byte?>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("ISACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PASSWORD");

                    b.Property<int?>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("ROL_ID");

                    b.HasKey("Id")
                        .HasName("PK__ADMINIST__3214EC27261094B9");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_ADMIN_EMAIL");

                    b.HasIndex("Identification")
                        .IsUnique()
                        .HasDatabaseName("UQ_ADMIN_IDENTIFICATION");

                    b.HasIndex("RolId");

                    b.ToTable("ADMINISTRATOR", (string)null);
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<byte>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<byte>("IsFrequent")
                        .HasColumnType("tinyint")
                        .HasColumnName("IS_FREQUENT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LOCATION");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MANAGER");

                    b.Property<string>("ManagerPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MANAGER_PHONE_NUMBER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NAME");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PHONE_NUMBER");

                    b.Property<int?>("QuantityPurchase")
                        .HasColumnType("int")
                        .HasColumnName("QUANTITY_PURCHASE");

                    b.Property<string>("SpecificLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SPECIFIC_LOCATION");

                    b.HasKey("Id")
                        .HasName("PK__CLIENT__3214EC2706FAB57E");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_CLIENT_EMAIL");

                    b.HasIndex("ManagerPhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_CLIENT_MANAGER_PHONE_NUMBER");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_CLIENT_PHONE_NUMBER");

                    b.ToTable("CLIENT", (string)null);
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.ClientPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("AMOUNT");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("ORDER_ID");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("PAYMENT_DATE");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PAYMENT_METHOD");

                    b.Property<string>("PhotoVoucherUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PHOTO_VOUCHER_URL");

                    b.HasKey("Id")
                        .HasName("PK__CLIENT_P__3214EC2724D43DD9");

                    b.HasIndex("OrderId");

                    b.ToTable("CLIENT_PAYMENT", (string)null);
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("IDENTIFICATION");

                    b.Property<byte?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PASSWORD");

                    b.Property<int?>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("ROL_ID");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SPECIALITY");

                    b.HasKey("Id")
                        .HasName("PK__EMPLOYEE__3214EC2784DED161");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_EMPLOYEE_EMAIL");

                    b.HasIndex("Identification")
                        .IsUnique()
                        .HasDatabaseName("UQ_EMPLOYEE_IDENTIFICATION");

                    b.HasIndex("RolId");

                    b.ToTable("EMPLOYEE", (string)null);
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("MATERIAL_ID");

                    b.Property<int>("MinimunQuantity")
                        .HasColumnType("int")
                        .HasColumnName("MINIMUN_QUANTITY");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("QUANTITY");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("STATE");

                    b.HasKey("Id")
                        .HasName("PK__INVENTOR__3214EC2756497961");

                    b.HasIndex("MaterialId");

                    b.ToTable("INVENTORY", (string)null);
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PHOTO_URL");

                    b.Property<decimal?>("PricePurchase")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("PRICE_PURCHASE");

                    b.HasKey("Id")
                        .HasName("PK__MATERIAL__3214EC27EDDBBA52");

                    b.ToTable("MATERIAL", (string)null);
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.MaterialSupplier", b =>
                {
                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("MATERIAL_ID");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("SUPPLIER_ID");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("QUANTITY");

                    b.HasKey("MaterialId", "SupplierId");

                    b.HasIndex("SupplierId");

                    b.ToTable("MATERIAL_SUPPLIER", (string)null);
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("ADMIN_ID");

                    b.Property<decimal>("Advancement")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("ADVANCEMENT");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("CLIENT_ID");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date")
                        .HasColumnName("CREATION_DATE");

                    b.Property<DateOnly>("DaliveryDate")
                        .HasColumnType("date")
                        .HasColumnName("DALIVERY_DATE");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("DISCOUNT");

                    b.Property<byte>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PRIORITY");

                    b.Property<string>("ResumePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RESUME_PATH");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("STATE");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("TOTAL_AMOUNT");

                    b.HasKey("Id")
                        .HasName("PK__ORDERS__3214EC270D9964BC");

                    b.HasIndex("AdminId");

                    b.HasIndex("ClientId");

                    b.ToTable("ORDERS", (string)null);
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CATEGORY");

                    b.Property<string>("Complexity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<byte>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<byte>("IsCustom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("IS_CUSTOM");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NAME");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PHOTO_URL");

                    b.Property<decimal>("PriceBase")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("PRICE_BASE");

                    b.HasKey("Id")
                        .HasName("PK__PRODUCTS__3214EC270CA74CC2");

                    b.ToTable("PRODUCTS", (string)null);
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.ProductMaterial", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("MaterialId");

                    b.HasKey("ProductId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("PRODUCT_MATERIAL", (string)null);
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.ProductOrder", b =>
                {
                    b.Property<int>("IdProduct")
                        .HasColumnType("int")
                        .HasColumnName("ID_PRODUCT");

                    b.Property<int>("IdOrder")
                        .HasColumnType("int")
                        .HasColumnName("ID_ORDER");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("QUANTITY");

                    b.HasKey("IdProduct", "IdOrder")
                        .HasName("PK__PRODUCT___2491A4768A57FE4F");

                    b.HasIndex("IdOrder");

                    b.ToTable("PRODUCT_ORDER", (string)null);
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NAME");

                    b.HasKey("Id")
                        .HasName("PK__ROL__3214EC27B04AB8DD");

                    b.ToTable("ROL", (string)null);
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("ROLE_ID");

                    b.Property<string>("Module")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MODULE");

                    b.Property<byte>("Cancreate")
                        .HasColumnType("tinyint")
                        .HasColumnName("CANCREATE");

                    b.Property<byte>("Candelete")
                        .HasColumnType("tinyint")
                        .HasColumnName("CANDELETE");

                    b.Property<byte>("Canedit")
                        .HasColumnType("tinyint")
                        .HasColumnName("CANEDIT");

                    b.Property<byte>("Canview")
                        .HasColumnType("tinyint")
                        .HasColumnName("CANVIEW");

                    b.HasKey("RoleId", "Module")
                        .HasName("PK__ROLE_PER__93B89656E74098C7");

                    b.ToTable("ROLE_PERMISSIONS", (string)null);
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADDRESS");

                    b.Property<DateTime?>("DateLastPurchase")
                        .HasColumnType("datetime")
                        .HasColumnName("DATE_LAST_PURCHASE");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NAME");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NOTES");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("PHONE");

                    b.HasKey("Id")
                        .HasName("PK__SUPPLIER__3214EC27FB64233E");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_SUPPLIER_EMAIL");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("UQ_SUPPLIER_PHONE");

                    b.ToTable("SUPPLIERS", (string)null);
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.Administrator", b =>
                {
                    b.HasOne("LAFABRICA.Data.DB.Rol", "Rol")
                        .WithMany("Administrators")
                        .HasForeignKey("RolId")
                        .HasConstraintName("FK__ADMINISTR__ROL_I__412EB0B6");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.ClientPayment", b =>
                {
                    b.HasOne("LAFABRICA.Data.DB.Order", "Order")
                        .WithMany("ClientPayments")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__CLIENT_PA__ORDER__6C190EBB");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.Employee", b =>
                {
                    b.HasOne("LAFABRICA.Data.DB.Rol", "Rol")
                        .WithMany("Employees")
                        .HasForeignKey("RolId")
                        .HasConstraintName("FK__EMPLOYEE__ROL_ID__44FF419A");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.Inventory", b =>
                {
                    b.HasOne("LAFABRICA.Data.DB.Material", "Material")
                        .WithMany("Inventories")
                        .HasForeignKey("MaterialId")
                        .HasConstraintName("FK__INVENTORY__MATER__68487DD7");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.MaterialSupplier", b =>
                {
                    b.HasOne("LAFABRICA.Data.DB.Material", "Material")
                        .WithMany("MaterialSuppliers")
                        .HasForeignKey("MaterialId")
                        .IsRequired();

                    b.HasOne("LAFABRICA.Data.DB.Supplier", "Supplier")
                        .WithMany("MaterialSuppliers")
                        .HasForeignKey("SupplierId")
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.Order", b =>
                {
                    b.HasOne("LAFABRICA.Data.DB.Administrator", "Admin")
                        .WithMany("Orders")
                        .HasForeignKey("AdminId")
                        .HasConstraintName("FK__ORDERS__ADMIN_ID__4D94879B");

                    b.HasOne("LAFABRICA.Data.DB.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .HasConstraintName("FK__ORDERS__CLIENT_I__4CA06362");

                    b.Navigation("Admin");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.ProductMaterial", b =>
                {
                    b.HasOne("LAFABRICA.Data.DB.Material", "Material")
                        .WithMany("ProductMaterials")
                        .HasForeignKey("MaterialId")
                        .IsRequired()
                        .HasConstraintName("FK__PRODUCT_MATERIAL__MaterialId");

                    b.HasOne("LAFABRICA.Data.DB.Product", "Product")
                        .WithMany("ProductMaterials")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__PRODUCT_MATERIAL__ProductId");

                    b.Navigation("Material");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.ProductOrder", b =>
                {
                    b.HasOne("LAFABRICA.Data.DB.Order", "IdOrderNavigation")
                        .WithMany("ProductOrders")
                        .HasForeignKey("IdOrder")
                        .IsRequired()
                        .HasConstraintName("FK__PRODUCT_O__ID_OR__5AEE82B9");

                    b.HasOne("LAFABRICA.Data.DB.Product", "IdProductNavigation")
                        .WithMany("ProductOrders")
                        .HasForeignKey("IdProduct")
                        .IsRequired()
                        .HasConstraintName("FK__PRODUCT_O__ID_PR__59FA5E80");

                    b.Navigation("IdOrderNavigation");

                    b.Navigation("IdProductNavigation");
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.RolePermission", b =>
                {
                    b.HasOne("LAFABRICA.Data.DB.Rol", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__ROLE_PERM__ROLE___3D5E1FD2");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.Administrator", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.Material", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("MaterialSuppliers");

                    b.Navigation("ProductMaterials");
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.Order", b =>
                {
                    b.Navigation("ClientPayments");

                    b.Navigation("ProductOrders");
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.Product", b =>
                {
                    b.Navigation("ProductMaterials");

                    b.Navigation("ProductOrders");
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.Rol", b =>
                {
                    b.Navigation("Administrators");

                    b.Navigation("Employees");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("LAFABRICA.Data.DB.Supplier", b =>
                {
                    b.Navigation("MaterialSuppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
